"""initial schema

Revision ID: 9f126b12f488
Revises:
Create Date: 2026-10-05 14:56:32.639473

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9f126b12f488"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("group_key", sa.String(length=64), nullable=True),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("shop_domain", sa.String(), nullable=True),
        sa.Column("token_env", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "vocab_learned",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_key", sa.String(length=64), nullable=False),
        sa.Column("field_key", sa.String(length=64), nullable=False),
        sa.Column("variant", sa.String(), nullable=False),
        sa.Column("canonical", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_key", "field_key", "variant"),
    )
    op.create_table(
        "batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("group_key", sa.String(length=64), nullable=False),
        sa.Column("store_key", sa.String(length=64), nullable=True),
        sa.Column("publish_status", sa.String(length=16), nullable=False),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind in ('new', 'audit')", name="kind_valid"),
        sa.ForeignKeyConstraint(
            ["store_key"],
            ["stores.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "store_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_filename", sa.String(), nullable=True),
        sa.Column("decided_by", sa.String(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("state in ('proposed', 'accepted', 'rejected')", name="state_valid"),
        sa.ForeignKeyConstraint(["store_key"], ["stores.key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_key", "version"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("ean", sa.String(length=14), nullable=True),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("research", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_batch_id"), "products", ["batch_id"], unique=False)
    op.create_index(op.f("ix_products_ean"), "products", ["ean"], unique=False)
    op.create_table(
        "store_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("store_key", sa.String(length=64), nullable=False),
        sa.Column("shopify_product_id", sa.String(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["store_key"],
            ["stores.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "store_key"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("actor", sa.String(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("store_product_id", sa.Integer(), nullable=True),
        sa.Column("field_key", sa.String(length=64), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["store_product_id"], ["store_products.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_at"), "events", ["at"], unique=False)
    op.create_table(
        "fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_product_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("alternatives", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("previous", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("value_en", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.String(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "origin in ('input', 'template', 'vocab', 'ai_research', 'ai_generated', 'auto_fix')",
            name="origin_valid",
        ),
        sa.CheckConstraint(
            "status in ('ok', 'suggested', 'fixed', 'warning', 'blocked')", name="status_valid"
        ),
        sa.CheckConstraint(
            "confidence is null or (confidence >= 0 and confidence <= 1)", name="confidence_range"
        ),
        sa.ForeignKeyConstraint(["store_product_id"], ["store_products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_product_id", "key"),
    )
    op.create_index(op.f("ix_fields_status"), "fields", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fields_status"), table_name="fields")
    op.drop_table("fields")
    op.drop_index(op.f("ix_events_at"), table_name="events")
    op.drop_table("events")
    op.drop_table("store_products")
    op.drop_index(op.f("ix_products_ean"), table_name="products")
    op.drop_index(op.f("ix_products_batch_id"), table_name="products")
    op.drop_table("products")
    op.drop_table("store_profiles")
    op.drop_table("batches")
    op.drop_table("vocab_learned")
    op.drop_table("stores")
    # ### end Alembic commands ###
