"""store product upload status

Revision ID: 15b204b6acbc
Revises: 5bb1099cb2cd
Create Date: 2026-10-06 07:17:46.476766

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15b204b6acbc"
down_revision: str | Sequence[str] | None = "5bb1099cb2cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("store_products", sa.Column("upload_status", sa.String(length=16), nullable=True))
    op.add_column("store_products", sa.Column("upload_message", sa.Text(), nullable=True))
    op.add_column("store_products", sa.Column("upload_attempted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store_products", "upload_attempted_at")
    op.drop_column("store_products", "upload_message")
    op.drop_column("store_products", "upload_status")
    # ### end Alembic commands ###
