"""vocab_learned status

Revision ID: 597def9c208e
Revises: a058609ef0d0
Create Date: 2026-10-05 18:54:57.551105

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "597def9c208e"
down_revision: str | Sequence[str] | None = "a058609ef0d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vocab_learned", sa.Column("status", sa.String(length=16), server_default="suggested", nullable=False)
    )
    op.add_column("vocab_learned", sa.Column("confidence", sa.Float(), nullable=True))
    op.add_column("vocab_learned", sa.Column("reason", sa.Text(), nullable=True))
    op.create_check_constraint("vocab_status_valid", "vocab_learned", "status in ('suggested', 'accepted', 'rejected')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("vocab_status_valid", "vocab_learned", type_="check")
    op.drop_column("vocab_learned", "reason")
    op.drop_column("vocab_learned", "confidence")
    op.drop_column("vocab_learned", "status")
    # ### end Alembic commands ###
