"""store product approval

Revision ID: 5bb1099cb2cd
Revises: 0716aa5bf6c1
Create Date: 2026-10-06 06:39:34.241123

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bb1099cb2cd"
down_revision: str | Sequence[str] | None = "0716aa5bf6c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("store_products", sa.Column("approved_by", sa.String(), nullable=True))
    op.add_column("store_products", sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store_products", "approved_at")
    op.drop_column("store_products", "approved_by")
    # ### end Alembic commands ###
