"""field issues

Revision ID: a058609ef0d0
Revises: 9f126b12f488
Create Date: 2026-10-05 15:15:31.027685

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a058609ef0d0"
down_revision: str | Sequence[str] | None = "9f126b12f488"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fields", sa.Column("issues", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fields", "issues")
    # ### end Alembic commands ###
