"""store settings

Revision ID: e647e6cbd3ef
Revises: 15b204b6acbc
Create Date: 2026-10-06 07:33:34.354324

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e647e6cbd3ef"
down_revision: str | Sequence[str] | None = "15b204b6acbc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stores", sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "settings")
    # ### end Alembic commands ###
